---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hkdcfgyd/n2motorsserv/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R demo $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH
    